from rest_framework import serializers

class ListSerializers(serializers.Serializer):
    name = serializers.CharField(read_only=True)
    create_name = serializers.CharField(read_only=True)
    t_code = serializers.CharField(read_only=True)
    aut1 = serializers.IntegerField(read_only=True)
    aut2 = serializers.IntegerField(read_only=True)
    aut3 = serializers.IntegerField(read_only=True)
    aut4 = serializers.IntegerField(read_only=True)
    aut5 = serializers.IntegerField(read_only=True)
    aut6 = serializers.IntegerField(read_only=True)
    aut7 = serializers.IntegerField(read_only=True)
    aut8 = serializers.IntegerField(read_only=True)
    aut9 = serializers.IntegerField(read_only=True)
    aut10 = serializers.IntegerField(read_only=True)
    aut11 = serializers.IntegerField(read_only=True)
    aut12 = serializers.IntegerField(read_only=True)
    aut13 = serializers.IntegerField(read_only=True)
    aut14 = serializers.IntegerField(read_only=True)
    aut15 = serializers.IntegerField(read_only=True)
    aut16 = serializers.IntegerField(read_only=True)
    aut17 = serializers.IntegerField(read_only=True)
    aut18 = serializers.IntegerField(read_only=True)
    aut19 = serializers.IntegerField(read_only=True)
    aut20 = serializers.IntegerField(read_only=True)
    create_time = serializers.DateTimeField(read_only=True, format='%Y-%m-%d %H:%M:%S')
    last_update_time = serializers.DateTimeField(read_only=True, format='%Y-%m-%d %H:%M:%S')

