from django.db import models

class ListModel(models.Model):
    name = models.CharField(max_length=50, verbose_name='商品编号')
    goods_name = models.CharField(max_length=50, verbose_name='商品描述')
    goods_l = models.FloatField(default=0, verbose_name='商品(长)')
    goods_w = models.FloatField(default=0, verbose_name='商品(宽)')
    goods_h = models.FloatField(default=0, verbose_name='商品(高)')
    goods_weight = models.FloatField(default=0, verbose_name='商品重量')
    goods_cost = models.FloatField(default=0, verbose_name='成本价(元)')
    goods_price1 = models.FloatField(default=0, verbose_name='一销价(元)')
    goods_price2 = models.FloatField(default=0, verbose_name='二销价(元)')
    goods_price3 = models.FloatField(default=0, verbose_name='三销价(元)')
    goods_unit = models.CharField(max_length=100, verbose_name='单位')
    goods_class = models.CharField(max_length=100, verbose_name='型号')
    goods_spacs = models.CharField(max_length=100, verbose_name='规格')
    goods_shape = models.CharField(max_length=100, verbose_name='形状')
    goods_color = models.CharField(max_length=100, verbose_name='颜色')
    goods_brand = models.CharField(max_length=100, verbose_name='品牌')
    goods_city = models.CharField(max_length=100, verbose_name='产地')
    appid = models.CharField(max_length=50, verbose_name='用户匹配码')
    create_name = models.CharField(max_length=50)
    t_code = models.CharField(max_length=50)
    is_delete = models.IntegerField(default=0)
    create_time = models.DateTimeField(auto_now_add=True)
    last_update_time = models.DateTimeField(auto_now=True)
