from rest_framework import serializers

class ListSerializers(serializers.Serializer):
    name = serializers.CharField(read_only=True)
    goods_name = serializers.CharField(read_only=True)
    goods_l = serializers.FloatField(read_only=True)
    goods_w = serializers.FloatField(read_only=True)
    goods_h = serializers.FloatField(read_only=True)
    goods_weight = serializers.FloatField(read_only=True)
    goods_cost = serializers.FloatField(read_only=True)
    goods_price1 = serializers.FloatField(read_only=True)
    goods_price2 = serializers.FloatField(read_only=True)
    goods_price3 = serializers.FloatField(read_only=True)
    goods_unit = serializers.CharField(read_only=True)
    goods_class = serializers.CharField(read_only=True)
    goods_spacs = serializers.CharField(read_only=True)
    goods_shape = serializers.CharField(read_only=True)
    goods_color = serializers.CharField(read_only=True)
    goods_brand = serializers.CharField(read_only=True)
    goods_city = serializers.CharField(read_only=True)
    create_name = serializers.CharField(read_only=True)
    t_code = serializers.CharField(read_only=True)
    create_time = serializers.DateTimeField(read_only=True, format='%Y-%m-%d %H:%M:%S')
    last_update_time = serializers.DateTimeField(read_only=True, format='%Y-%m-%d %H:%M:%S')
