# Generated by Django 4.1.2 on 2025-11-07 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listmodel",
            name="creater",
        ),
        migrations.RemoveField(
            model_name="listmodel",
            name="customer_address",
        ),
        migrations.RemoveField(
            model_name="listmodel",
            name="customer_city",
        ),
        migrations.RemoveField(
            model_name="listmodel",
            name="customer_level",
        ),
        migrations.RemoveField(
            model_name="listmodel",
            name="customer_manager",
        ),
        migrations.RemoveField(
            model_name="listmodel",
            name="update_time",
        ),
        migrations.AddField(
            model_name="listmodel",
            name="customer_bank_account",
            field=models.CharField(
                default="", max_length=255, verbose_name="Bank Account"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="listmodel",
            name="customer_film_laminating_fee",
            field=models.BigIntegerField(default=0, verbose_name="Film-Laminating Fee"),
        ),
        migrations.AddField(
            model_name="listmodel",
            name="customer_group",
            field=models.CharField(default="", max_length=255, verbose_name="Group"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="listmodel",
            name="customer_id",
            field=models.CharField(default="", max_length=255, verbose_name="ID"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="listmodel",
            name="customer_loading_fee",
            field=models.BigIntegerField(default=0, verbose_name="Loading Fee"),
        ),
        migrations.AddField(
            model_name="listmodel",
            name="customer_password",
            field=models.CharField(default="", max_length=255, verbose_name="Password"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="listmodel",
            name="customer_refrigeration_fee",
            field=models.BigIntegerField(default=0, verbose_name="Refrigeration Fee"),
        ),
        migrations.AlterField(
            model_name="listmodel",
            name="create_time",
            field=models.DateTimeField(max_length=255, verbose_name="Create Time"),
        ),
        migrations.AlterField(
            model_name="listmodel",
            name="customer_contact",
            field=models.CharField(max_length=255, verbose_name="Contact"),
        ),
        migrations.AlterField(
            model_name="listmodel",
            name="customer_name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
    ]
