# Generated by Django 2.2.12 on 2020-07-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetailModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appid', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('so_status', models.IntegerField(default=1)),
                ('goods_code', models.CharField(max_length=50)),
                ('goods_name', models.CharField(max_length=50)),
                ('so_qty', models.IntegerField(default=0)),
                ('pick_stock', models.IntegerField(default=0)),
                ('pick_down_qty', models.IntegerField(default=0)),
                ('picked_stock', models.IntegerField(default=0)),
                ('picked_down_qty', models.IntegerField(default=0)),
                ('oos_qty', models.IntegerField(default=0)),
                ('shipping_qty', models.IntegerField(default=0)),
                ('receive_qty', models.IntegerField(default=0)),
                ('damage_qty', models.IntegerField(default=0)),
                ('shortage_qty', models.IntegerField(default=0)),
                ('customer', models.CharField(max_length=50)),
                ('create_name', models.CharField(max_length=50)),
                ('t_code', models.CharField(max_length=50)),
                ('is_delete', models.IntegerField(default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ListModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appid', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('so_status', models.IntegerField(default=1)),
                ('create_name', models.CharField(max_length=50)),
                ('customer', models.CharField(max_length=50)),
                ('t_code', models.CharField(max_length=50)),
                ('is_delete', models.IntegerField(default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PickingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appid', models.CharField(max_length=50)),
                ('bin_name', models.CharField(max_length=50)),
                ('so_name', models.CharField(max_length=50)),
                ('picking_status', models.IntegerField(default=0)),
                ('goods_code', models.CharField(max_length=50)),
                ('goods_name', models.CharField(max_length=50)),
                ('pick_stock', models.IntegerField(default=0)),
                ('picked_stock', models.IntegerField(default=0)),
                ('shipping_stock', models.IntegerField(default=0)),
                ('customer', models.CharField(max_length=50)),
                ('picking_people', models.CharField(max_length=50)),
                ('create_name', models.CharField(max_length=50)),
                ('t_code', models.CharField(max_length=50)),
                ('is_delete', models.IntegerField(default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
