# Generated by Django 3.1.3 on 2020-11-25 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('binset', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listmodel',
            name='warehouse_name',
        ),
    ]
