# Generated by Django 2.2.12 on 2020-07-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='姓名')),
                ('mobile', models.CharField(max_length=11, verbose_name='手机号')),
                ('comments', models.CharField(max_length=400, verbose_name='备注')),
                ('openid', models.CharField(max_length=400, verbose_name='用户标识')),
                ('ip', models.CharField(max_length=80, verbose_name='ip')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
