# Generated by Django 3.1.4 on 2021-02-21 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=100, verbose_name='Sender')),
                ('receiver', models.CharField(max_length=100, verbose_name='Receiver')),
                ('read', models.BooleanField(default=False, verbose_name='Readed')),
                ('detail', models.CharField(max_length=100, verbose_name='Chat text')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Delete label')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create time')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Update time')),
            ],
            options={
                'verbose_name': 'data id',
                'verbose_name_plural': 'data id',
                'db_table': 'chat',
                'ordering': ['-id'],
            },
        ),
    ]
