# Generated by Django 2.2.12 on 2020-07-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='库位名称')),
                ('goods_code', models.CharField(max_length=50, verbose_name='商品编号')),
                ('goods_name', models.CharField(max_length=50, verbose_name='商品描述')),
                ('goods_qty', models.BigIntegerField(default=0, verbose_name='盘点数量')),
                ('staff', models.CharField(max_length=50, verbose_name='盘点用户名')),
                ('cycle_count_balance', models.BigIntegerField(default=0, verbose_name='盘点差异')),
                ('inbound_time', models.DateTimeField()),
                ('appid', models.CharField(max_length=50, verbose_name='用户匹配码')),
                ('t_code', models.CharField(max_length=50)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
