# Generated by Django 3.1.14 on 2022-01-06 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=255, verbose_name='Openid')),
                ('appid', models.CharField(max_length=255, verbose_name='Appid')),
                ('ip', models.CharField(max_length=32, verbose_name='IP')),
                ('method', models.CharField(max_length=18, verbose_name='Method')),
                ('t_code', models.CharField(max_length=255, verbose_name='Transaction Code')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
            ],
            options={
                'verbose_name': 'data id',
                'verbose_name_plural': 'data id',
                'db_table': 'throttle',
                'ordering': ['-id'],
            },
        ),
    ]
