# Generated by Django 4.1.2 on 2025-10-29 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=255, verbose_name='Openid')),
                ('appid', models.CharField(max_length=255, verbose_name='Appid')),
                ('ip', models.CharField(max_length=255, verbose_name='IP')),
                ('method', models.CharField(max_length=18, verbose_name='Method')),
                ('t_code', models.CharField(max_length=255, verbose_name='Transaction Code')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
            ],
            options={
                'verbose_name': 'Throttle',
                'verbose_name_plural': 'Throttle',
                'db_table': 'throttle',
                'ordering': ['-id'],
            },
        ),
    ]
