# Generated by Django 2.2.12 on 2020-07-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Throttle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=100, verbose_name='匹配名')),
                ('appid', models.CharField(max_length=100, verbose_name='匹配用户码')),
                ('transaction_code', models.CharField(max_length=100, verbose_name='事务代码')),
                ('mode', models.CharField(max_length=100, verbose_name='事务类型')),
                ('ip_address', models.CharField(max_length=100, verbose_name='ip地址')),
                ('throttle_create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
