# Generated by Django 4.1.2 on 2025-10-31 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="listmodel",
            name="customer_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Customer ID"
            ),
        ),
    ]
