# Generated by Django 3.1.3 on 2020-11-26 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_listmodel_unit_volum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listmodel',
            old_name='unit_volum',
            new_name='unit_volume',
        ),
    ]
