# Generated by Django 2.2.12 on 2020-07-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QrCodeList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, verbose_name='二维码信息')),
                ('text_img', models.CharField(max_length=100, verbose_name='二维码链接')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
