# Generated by Django 3.1.3 on 2020-11-25 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asnlistmodel',
            name='transportation_fee',
            field=models.JSONField(default=dict, verbose_name='Transportation Fee'),
        ),
    ]
