# Generated by Django 3.1.3 on 2020-11-25 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asn', '0002_auto_20201125_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asnlistmodel',
            name='supplier',
            field=models.CharField(max_length=255, verbose_name='ASN Supplier'),
        ),
    ]
