# Generated by Django 3.1.3 on 2020-11-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asn', '0003_auto_20201125_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='asndetailmodel',
            name='asn_supplier',
            field=models.CharField(default=1, max_length=255, verbose_name='ASN Supplier'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asndetailmodel',
            name='transportation_fee',
            field=models.JSONField(default=dict, verbose_name='Transportation Fee'),
        ),
    ]
