# Generated by Django 3.1.3 on 2020-11-25 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asn', '0004_auto_20201125_1313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asndetailmodel',
            old_name='asn_supplier',
            new_name='supplier',
        ),
    ]
