# Generated by Django 3.1.3 on 2020-11-25 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asn', '0005_auto_20201125_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asndetailmodel',
            name='goods_qty',
            field=models.IntegerField(default=0, verbose_name='Goods QTY'),
        ),
    ]
