# Generated by Django 3.1.3 on 2020-11-25 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asn', '0006_auto_20201125_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asndetailmodel',
            name='transportation_fee',
        ),
    ]
