# Generated by Django 3.1.3 on 2020-11-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asn', '0007_remove_asndetailmodel_transportation_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asndetailmodel',
            name='supplier',
            field=models.CharField(default='', max_length=255, verbose_name='ASN Supplier'),
        ),
        migrations.AlterField(
            model_name='asnlistmodel',
            name='supplier',
            field=models.CharField(default='', max_length=255, verbose_name='ASN Supplier'),
        ),
    ]
