# Generated by Django 3.1.3 on 2020-11-26 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asn', '0009_auto_20201125_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='asndetailmodel',
            name='goods_volume',
            field=models.FloatField(default=0, verbose_name='Goods Volume'),
        ),
        migrations.AddField(
            model_name='asndetailmodel',
            name='goods_weight',
            field=models.FloatField(default=0, verbose_name='Goods Weight'),
        ),
        migrations.AddField(
            model_name='asnlistmodel',
            name='total_volume',
            field=models.FloatField(default=0, verbose_name='Total Volume'),
        ),
        migrations.AddField(
            model_name='asnlistmodel',
            name='total_weight',
            field=models.FloatField(default=0, verbose_name='Total Weight'),
        ),
    ]
