# Generated by Django 3.1.3 on 2020-11-26 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asn', '0010_auto_20201126_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asndetailmodel',
            name='asn_status',
            field=models.IntegerField(default=0, verbose_name='ASN Status'),
        ),
        migrations.AlterField(
            model_name='asnlistmodel',
            name='asn_status',
            field=models.IntegerField(default=0, verbose_name='ASN Status'),
        ),
    ]
