# Generated by Django 3.1.3 on 2020-11-26 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asn', '0012_asndetailmodel_goods_actual_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asndetailmodel',
            name='asn_status',
            field=models.IntegerField(default=1, verbose_name='ASN Status'),
        ),
        migrations.AlterField(
            model_name='asnlistmodel',
            name='asn_status',
            field=models.IntegerField(default=1, verbose_name='ASN Status'),
        ),
    ]
