# Generated by Django 3.1.3 on 2020-11-27 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asn', '0013_auto_20201126_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='asndetailmodel',
            name='comments',
            field=models.CharField(default='', max_length=255, verbose_name='Comments'),
        ),
    ]
