# Generated by Django 3.1.3 on 2020-11-29 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asn', '0014_asndetailmodel_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asndetailmodel',
            name='comments',
        ),
        migrations.AddField(
            model_name='asndetailmodel',
            name='goods_shortage_qty',
            field=models.IntegerField(default=0, verbose_name='Goods Shortage QTY'),
        ),
    ]
