# Generated by Django 3.1.3 on 2020-12-01 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asn', '0016_asndetailmodel_goods_more_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='asndetailmodel',
            name='sorted_qty',
            field=models.IntegerField(default=0, verbose_name='Goods Actual QTY'),
        ),
    ]
