# Generated by Django 3.1.3 on 2020-12-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asn', '0017_asndetailmodel_sorted_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='asndetailmodel',
            name='goods_damage_qty',
            field=models.IntegerField(default=0, verbose_name='Goods More QTY'),
        ),
    ]
